#!/bin/bash
# My first script
export LC_COLLATE=C 
echo "startar tokenizer och sortering"
STARTTIME=$(date +%s)
./tokenizer < testfil | sort > ut
ENDTIME=$(date +%s)
echo "tokenizer och sorteringen är klar"
echo "det tog $(($ENDTIME - $STARTTIME)) sekunder"
