#!/bin/bash
# My first script
export LC_COLLATE=C 
echo "startar tokenizer och sortering"
STARTTIME=$(date +%s)
/info/adk15/labb1/tokenizer < //afs/nada.kth.se/home/6/u1ve7an6/Documents/adk/testfil | sort > /var/tmp/ut
ENDTIME=$(date +%s)
echo "tokenizer och sorteringen är klar"
echo "det tog $(($ENDTIME - $STARTTIME)) sekunder"
